blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/home/student/.pyenv/versions/miniconda3-latest/bin/python
- -DPYTHON_INCLUDE_DIR=/home/student/.pyenv/versions/miniconda3-latest/include/python3.7m
- -DPYTHON_LIBRARY=/home/student/.pyenv/versions/miniconda3-latest/lib/libpython3.7m.so
devel_layout: linked
devel_space: devel
extend_path: null
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
